pipeline {
    agent any

    stages {
        stage('Lint') {
             steps {
                sh './gradlew lint'
             }
        }
        stage('SonarQube') {
            steps {
                script {
                    sonarqubeScannerHome = tool 'SonarQubeScanner'
                }
                withSonarQubeEnv('SonarQube') {
                    sh "${sonarqubeScannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Build') {
             steps {
                sh './gradlew clean && rm -rf ./app/build/'
                sh './gradlew assembleDebug'
             }
        }
       stage('UnitTest') {
             steps {
                sh './gradlew test'
             }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'app/build/outputs/**/*.apk', fingerprint: true
            }
        }
    }
}